// pearl_gemm_capi.cpp — C-ABI shim around pearl-gemm kernels.
//
// Phase 1b: torch-free build. This translation unit is compiled into
// libpearl_gemm_capi.so without any libtorch / libpython dependency.
// `<c10/util/Exception.h>` and `<torch/types.h>` resolve to stubs in
// csrc/capi/stub_torch (added via -Icsrc/capi/stub_torch).
//
// Status code convention:
//   0          success
//   <0         failure (negative cudaError_t-equivalent or shim-defined)

#include <cuda_runtime.h>
#include <algorithm>
#include <cstdint>
#include <cstring>
#include <stdexcept>

#include "tensor_hash/tensor_hash_decl.hpp"
#include "blake3/blake3_constants.hpp"
#include "gemm/pearl_api_params.h"
#include "gemm/pearl_gemm_decl.h"
#include "gemm/host_signal_header.hpp"
#include "gemm/heuristics.hpp"
#include "gemm/static_switch.h"
#ifndef PEARL_GEMM_PORTABLE
#include "gemm/static_switch_matmul.h"
#include "gemm/static_switch_noisingA.h"
#endif

#include "pearl_gemm_capi.h"

#include <cutlass/numeric_types.h>

#ifdef PEARL_GEMM_PORTABLE
#include "portable_int8_helpers.h"
#include "portable/transcript_kernel.cuh"
#include "gemm/host_signal_header.hpp"
#ifdef PEARL_GEMM_B200
#include "blackwell/transcript_gemm_sm100.h"
#endif
#endif

// --- internal: cached per-device cudaDeviceProp ---------------------------
namespace {

constexpr int kMaxDevices = 16;
cudaDeviceProp g_dprops[kMaxDevices];
bool g_dprops_valid[kMaxDevices] = {false};

cudaDeviceProp* get_dprops_locked(int device_id) {
  if (device_id < 0 || device_id >= kMaxDevices) return nullptr;
  if (!g_dprops_valid[device_id]) {
    if (cudaGetDeviceProperties(&g_dprops[device_id], device_id) != cudaSuccess)
      return nullptr;
    g_dprops_valid[device_id] = true;
  }
  return &g_dprops[device_id];
}

int current_device_or(int fallback) {
  int dev = fallback;
  if (cudaGetDevice(&dev) != cudaSuccess) return fallback;
  return dev;
}

int transcript_launch_rc(cudaError_t err) {
  return err == cudaSuccess ? 0 : -34000 - static_cast<int>(err);
}

int transcript_finalize_rc(cudaError_t err) {
  return err == cudaSuccess ? 0 : -35000 - static_cast<int>(err);
}

int g_salted_seed = 0;

}  // namespace

// --- public C ABI ----------------------------------------------------------
// Symbol export: on Windows the DLL's exports are generated by CMake
// (WINDOWS_EXPORT_ALL_SYMBOLS), and adding __declspec(dllexport) here would
// clash with the plain declarations in pearl_gemm_capi.h ("redeclaration
// cannot add dllexport"), so it's a no-op there. Elsewhere the build compiles
// with -fvisibility=hidden, so this attribute is what makes the C ABI visible.
#if defined(_WIN32)
#  define PEARL_CAPI_EXPORT
#else
#  define PEARL_CAPI_EXPORT __attribute__((visibility("default")))
#endif
extern "C" {

PEARL_CAPI_EXPORT void pearl_capi_set_salted_seed(int on) {
  g_salted_seed = on ? 1 : 0;
}

PEARL_CAPI_EXPORT int pearl_capi_get_salted_seed(void) {
  return g_salted_seed;
}

PEARL_CAPI_EXPORT int pearl_capi_abi_version(void) { return 2; }

PEARL_CAPI_EXPORT const char* pearl_capi_build_profile(void) {
#if defined(PEARL_GEMM_VOLTA)
  return "volta";
#elif defined(PEARL_GEMM_TURING)
  return "turing";
#elif defined(PEARL_GEMM_B200)
  return "b200";
#elif defined(PEARL_GEMM_BLACKWELL)
  return "blackwell";
#elif defined(PEARL_GEMM_ADA)
  return "ada";
#elif defined(PEARL_GEMM_AMPERE)
  return "ampere";
#elif defined(PEARL_GEMM_PORTABLE)
  return "portable";
#else
  return "h100";
#endif
}

PEARL_CAPI_EXPORT int pearl_capi_supports_sm(int major, int minor) {
#if defined(PEARL_GEMM_VOLTA)
  return major == 7 && minor == 0;
#elif defined(PEARL_GEMM_TURING)
  return major == 7 && minor == 5;
#elif defined(PEARL_GEMM_B200)
  return major == 10 && minor == 0;
#elif defined(PEARL_GEMM_BLACKWELL)
  return (major == 12) && (minor == 0 || minor == 1);   // 12.0 = 5090, 12.1 = GB10
#elif defined(PEARL_GEMM_ADA)
  return major == 8 && minor == 9;
#elif defined(PEARL_GEMM_AMPERE)
  return major == 8 && (minor == 0 || minor == 6);
#elif defined(PEARL_GEMM_PORTABLE)
  return major == 8 && (minor == 0 || minor == 6);
#else
  return major == 9 && minor == 0;
#endif
}

PEARL_CAPI_EXPORT int pearl_capi_get_host_signal_sync_size(void) {
  return static_cast<int>(sizeof(HostSignalSync));
}

PEARL_CAPI_EXPORT int pearl_capi_get_host_signal_header_size(void) {
  return static_cast<int>(host_signal_header_size);
}

PEARL_CAPI_EXPORT int64_t pearl_capi_get_required_scratchpad_bytes(
    int64_t matrix_bytes, int threads_per_block) {
  size_t bytes_per_block =
      static_cast<size_t>(threads_per_block) * blake3::CHUNK_SIZE;
  size_t required_blocks =
      (static_cast<size_t>(matrix_bytes) + bytes_per_block - 1) /
      bytes_per_block;
  return static_cast<int64_t>(required_blocks * blake3::CHAINING_VALUE_SIZE);
}

PEARL_CAPI_EXPORT int pearl_capi_tensor_hash(const uint8_t* data,
                            uint32_t data_size,
                            uint8_t* out,
                            const uint8_t* key,
                            uint32_t num_blocks,
                            uint32_t threads_per_block,
                            uint32_t num_stages,
                            uint32_t leaves_per_mt_block,
                            uint8_t* roots,
                            int device_id,
                            void* stream_void) {
  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  cudaDeviceProp* dprops = get_dprops_locked(device_id);
  if (!dprops) return -1;
  try {
    tensor_hash(data, data_size, out, key, num_blocks, threads_per_block,
                num_stages, leaves_per_mt_block, roots, *dprops, stream);
  } catch (const std::exception&) {
    return -2;
  }
  return 0;
}

PEARL_CAPI_EXPORT int pearl_capi_tensor_hash_leaf_cvs(
                            const uint8_t* data,
                            uint32_t data_size,
                            uint8_t* out,
                            const uint8_t* key,
                            uint32_t num_blocks,
                            uint32_t threads_per_block,
                            uint32_t num_stages,
                            uint32_t leaves_per_mt_block,
                            uint8_t* roots,
                            uint8_t* leaf_cvs,
                            int device_id,
                            void* stream_void) {
  if (data == nullptr || out == nullptr || key == nullptr ||
      roots == nullptr || leaf_cvs == nullptr) {
    return -1;
  }
  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  cudaDeviceProp* dprops = get_dprops_locked(device_id);
  if (!dprops) return -1;
  try {
    tensor_hash_with_leaf_cvs(
        data, data_size, out, key, num_blocks, threads_per_block,
        num_stages, leaves_per_mt_block, roots, leaf_cvs, *dprops, stream);
  } catch (const std::exception&) {
    return -2;
  }
  return 0;
}

PEARL_CAPI_EXPORT int pearl_capi_bseed_expand_and_tensor_hash(
                            const uint8_t* bseed,
                            uint8_t* data,
                            uint32_t data_size,
                            uint8_t* out,
                            const uint8_t* key,
                            uint32_t num_blocks,
                            uint32_t threads_per_block,
                            uint32_t num_stages,
                            uint32_t leaves_per_mt_block,
                            uint8_t* roots,
                            int device_id,
                            void* stream_void) {
  if (bseed == nullptr || data == nullptr || out == nullptr ||
      key == nullptr || roots == nullptr) {
    return -1;
  }
  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  cudaDeviceProp* dprops = get_dprops_locked(device_id);
  if (!dprops) return -1;
  try {
    bseed_expand_and_tensor_hash(
        bseed, data, data_size, out, key, num_blocks, threads_per_block,
        num_stages, leaves_per_mt_block, roots, *dprops, stream);
  } catch (const std::exception&) {
    return -2;
  }
  return 0;
}

PEARL_CAPI_EXPORT int pearl_capi_bseed_expand_and_tensor_hash_leaf_cvs(
                            const uint8_t* bseed,
                            uint8_t* data,
                            uint32_t data_size,
                            uint8_t* out,
                            const uint8_t* key,
                            uint32_t num_blocks,
                            uint32_t threads_per_block,
                            uint32_t num_stages,
                            uint32_t leaves_per_mt_block,
                            uint8_t* roots,
                            uint8_t* leaf_cvs,
                            int device_id,
                            void* stream_void) {
  if (bseed == nullptr || data == nullptr || out == nullptr ||
      key == nullptr || roots == nullptr || leaf_cvs == nullptr) {
    return -1;
  }
  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  cudaDeviceProp* dprops = get_dprops_locked(device_id);
  if (!dprops) return -1;
  try {
    bseed_expand_and_tensor_hash_with_leaf_cvs(
        bseed, data, data_size, out, key, num_blocks, threads_per_block,
        num_stages, leaves_per_mt_block, roots, leaf_cvs, *dprops, stream);
  } catch (const std::exception&) {
    return -2;
  }
  return 0;
}

PEARL_CAPI_EXPORT int pearl_capi_commitment_hash_from_merkle_roots(
                                                  const uint8_t* A_merkle_root,
                                                  const uint8_t* B_merkle_root,
                                                  const uint8_t* key,
                                                  uint8_t* A_commitment_hash,
                                                  uint8_t* B_commitment_hash,
                                                  int device_id,
                                                  void* stream_void) {
  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  cudaDeviceProp* dprops = get_dprops_locked(device_id);
  if (!dprops) return -1;
  try {
    bool apply_salt = (g_salted_seed != 0);
    commitment_hash_from_merkle_roots(A_merkle_root, B_merkle_root, key,
                                      A_commitment_hash, B_commitment_hash,
                                      apply_salt, 131072, 131072,
                                      *dprops, stream);
  } catch (const std::exception&) {
    return -2;
  }
  return 0;
}

PEARL_CAPI_EXPORT int pearl_capi_noise_gen(int R,
                          int m, int n, int k,
                          void* EAL,
                          void* EAL_fp16,
                          void* EAR_R_major,
                          void* EAR_K_major,
                          void* EBL_R_major,
                          void* EBL_K_major,
                          void* EBR,
                          void* EBR_fp16,
                          const uint8_t* key_A,
                          const uint8_t* key_B,
                          void* stream_void) {
  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  Noise_gen_params params{};
  params.ptr_EAL = EAL;
  params.ptr_EAL_fp16 = EAL_fp16;
  params.ptr_EAR_R_major = EAR_R_major;
  params.ptr_EAR_K_major = EAR_K_major;
  params.ptr_EBL_R_major = EBL_R_major;
  params.ptr_EBL_K_major = EBL_K_major;
  params.ptr_EBR = EBR;
  params.ptr_EBR_fp16 = EBR_fp16;
  params.m = m;
  params.n = n;
  params.k = k;
  params.r = R;
  params.ptr_key_A = const_cast<uint8_t*>(key_A);
  params.ptr_key_B = const_cast<uint8_t*>(key_B);
  params.ptr_aux_buffer = nullptr;
  params.aux_buffer_size = 0;

  try {
    if (R == 64) {
      run_noise_generation<64, 64>(params, stream);
    } else if (R == 128) {
      run_noise_generation<128, 64>(params, stream);
    } else if (R == 256) {
      run_noise_generation<256, 64>(params, stream);   // GB10 / stratum mainnet (HeroMiners)
    } else {
      return -4;
    }
  } catch (const std::exception&) {
    return -2;
  }
  return 0;
}

}  // extern "C"

// --- noise_B & noisy_gemm: torch-free dispatch -----------------------------
//
// Mirrors the body of `noise_B` / `noisy_gemm` in csrc/gemm/pearl_gemm_api.cpp
// but builds PearlAPIParams directly from the C-ABI struct's raw void*
// pointers, fetches dprops via cudaGetDeviceProperties, takes the stream
// from the C-ABI argument (rather than at::cuda::getCurrentCUDAStream),
// and hard-codes the fp16 noising path (skip int32 split-K — pure-miner
// never uses it).

// Internal layout of a pearl-gemm workspace handle.  One contiguous device
// allocation, sliced into three sub-buffers (each 256-byte-aligned):
//
//   [ noiseA_scratch ][ noiseB_scratch ][ transcript ]
//
// The handle is opaque to callers (passed as void* through the C ABI).
namespace {

constexpr size_t kWorkspaceAlign = 256;

inline size_t align_up(size_t x, size_t a) { return (x + a - 1) & ~(a - 1); }

struct PearlCapiWorkspace {
  void*   base_ptr;
  size_t  total_bytes;
  size_t  off_noiseA;
  size_t  off_noiseB;
  size_t  off_transcript;
  size_t  na_bytes;
  size_t  nb_bytes;
  size_t  transcript_bytes;
  int32_t m, n, k, r;
  int     with_noise_A;
  int     with_noise_B;
  int     device_id = 0;

  // Cached per-σ constants — populated by pearl_capi_workspace_install_params.
  // Default-initialised to zero; params_installed gates pearl_capi_iter use.
  bool                      params_installed = false;
  PearlCapiWorkspaceParams  params{};
  PearlCapiNoisyGemmParams  ng_template{};  // pre-built, only header_ptr varies

  // Optional CUDA graph for the fixed-size IterBatch hot path.
  bool             graph_ready = false;
  int32_t          graph_batch_count = 0;
  cudaGraph_t      iter_graph = nullptr;
  cudaGraphExec_t  iter_graph_exec = nullptr;
  uint64_t*        graph_seed_lo_host = nullptr;  // pinned host slot
  uint64_t*        graph_seed_lo_dev = nullptr;   // device slot

  void* noiseA_ptr() const {
    return na_bytes ? static_cast<char*>(base_ptr) + off_noiseA : nullptr;
  }
  void* noiseB_ptr() const {
    return nb_bytes ? static_cast<char*>(base_ptr) + off_noiseB : nullptr;
  }
  void* transcript_ptr() const {
    return transcript_bytes ? static_cast<char*>(base_ptr) + off_transcript
                            : nullptr;
  }
};

void destroy_iter_graph(PearlCapiWorkspace* ws) {
  if (!ws) return;
  if (ws->iter_graph_exec) {
    cudaGraphExecDestroy(ws->iter_graph_exec);
    ws->iter_graph_exec = nullptr;
  }
  if (ws->iter_graph) {
    cudaGraphDestroy(ws->iter_graph);
    ws->iter_graph = nullptr;
  }
  if (ws->graph_seed_lo_dev) {
    cudaFree(ws->graph_seed_lo_dev);
    ws->graph_seed_lo_dev = nullptr;
  }
  if (ws->graph_seed_lo_host) {
    cudaFreeHost(ws->graph_seed_lo_host);
    ws->graph_seed_lo_host = nullptr;
  }
  ws->graph_ready = false;
  ws->graph_batch_count = 0;
}

}  // namespace

extern "C" {

PEARL_CAPI_EXPORT int pearl_capi_workspace_alloc(int32_t m, int32_t n,
                                                  int32_t k, int32_t r,
                                                  int with_noise_A,
                                                  int with_noise_B,
                                                  void** out_workspace,
                                                  void* stream_void) {
  if (!out_workspace) return -1;
  *out_workspace = nullptr;
  if (m < 0 || n < 0 || k < 0 || r <= 0) return -2;
  try {
    cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
    auto* ws = new PearlCapiWorkspace{};
    ws->m = m; ws->n = n; ws->k = k; ws->r = r;
    ws->with_noise_A = with_noise_A;
    ws->with_noise_B = with_noise_B;

#ifdef PEARL_GEMM_PORTABLE
    using namespace pearl::capi::portable;

    ws->na_bytes = with_noise_A
        ? std::max(scratch_bytes_for_matmul_i32(m, r),
                   scratch_bytes_for_matmul_i32(m, k))
        : 0;
    ws->nb_bytes = with_noise_B
        ? std::max(scratch_bytes_for_matmul_i32(n, k),
                   scratch_bytes_for_matmul_i32(n, r))
        : 0;
    ws->transcript_bytes = with_noise_A
        ? sizeof(uint32_t) *
          static_cast<size_t>(pearl::portable::transcript_buffer_elems(m, n, 1))
        : 0;
#else
    // H100 / CUTLASS path doesn't use these helpers — workspace is a no-op
    // pass-through that callers can still hand to the C-ABI without
    // branching on build flavour.
    ws->na_bytes = 0;
    ws->nb_bytes = 0;
    ws->transcript_bytes = 0;
#endif

    ws->off_noiseA     = 0;
    ws->off_noiseB     = align_up(ws->off_noiseA + ws->na_bytes, kWorkspaceAlign);
    ws->off_transcript = align_up(ws->off_noiseB + ws->nb_bytes, kWorkspaceAlign);
    ws->total_bytes    = ws->off_transcript + ws->transcript_bytes;

    if (ws->total_bytes > 0) {
      if (cudaMallocAsync(&ws->base_ptr, ws->total_bytes, stream)
          != cudaSuccess) {
        delete ws;
        return -30;
      }
    } else {
      ws->base_ptr = nullptr;
    }

    *out_workspace = ws;
    return 0;
  } catch (const std::exception&) {
    return -2;
  }
}

PEARL_CAPI_EXPORT int pearl_capi_workspace_free(void* workspace,
                                                 void* stream_void) {
  if (!workspace) return 0;
  auto* ws = static_cast<PearlCapiWorkspace*>(workspace);
  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  int rc = 0;
  destroy_iter_graph(ws);
  if (ws->base_ptr) {
    if (cudaFreeAsync(ws->base_ptr, stream) != cudaSuccess) rc = -31;
  }
  delete ws;
  return rc;
}

PEARL_CAPI_EXPORT int pearl_capi_noise_B(const PearlCapiNoiseBParams* p,
                                          void* stream_void) {
  if (!p) return -1;
  try {
    cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
#ifdef PEARL_GEMM_PORTABLE
    // Portable path — torch-free mirror of noise_B_portable_impl in
    // csrc/gemm/pearl_gemm_api.cpp. Uses cuBLASLt int8 GEMM + the small
    // add/clamp/divide kernels from portable_int8_helpers.cu.
    using namespace pearl::capi::portable;
    const int n = p->n, k = p->k, r = p->r;

    // Scratchpad: largest int32 product is (n,k); reused for (n,r).
    // Use the per-σ workspace pool when supplied (avoids per-call
    // cudaMallocAsync/Free hit — measurable on the portable hot loop).
    int32_t* scratch = nullptr;
    bool scratch_owned = false;
    auto* ws = static_cast<PearlCapiWorkspace*>(p->workspace);
    size_t scratch_bytes = std::max(scratch_bytes_for_matmul_i32(n, k),
                                    scratch_bytes_for_matmul_i32(n, r));
    if (ws && ws->nb_bytes >= scratch_bytes && ws->noiseB_ptr() != nullptr) {
      scratch = static_cast<int32_t*>(ws->noiseB_ptr());
    } else {
      if (cudaMallocAsync(reinterpret_cast<void**>(&scratch), scratch_bytes,
                          stream) != cudaSuccess) return -30;
      scratch_owned = true;
    }
    int rc = 0;

    // BpEB = clamp(B + EBR @ EBL_R_major.T, ±127)   shapes: (n,k) + (n,r)@(r,k)
    rc = int8_add_clamp_to_int8(
        static_cast<const int8_t*>(p->B),
        static_cast<const int8_t*>(p->EBR),
        static_cast<const int8_t*>(p->EBL_R_major),
        static_cast<int8_t*>(p->BpEB),
        scratch, n, k, r, stream);
    if (rc != 0) {
      if (scratch_owned) cudaFreeAsync(scratch, stream);
      return rc;
    }

    // EARxBpEB_fp16 = (BpEB @ EAR_K_major.T) / 2^12   shapes: (n,k)@(k,r) → (n,r)
    rc = int8_matmul_into_fp16_div(
        static_cast<const int8_t*>(p->BpEB),
        static_cast<const int8_t*>(p->EAR_K_major),
        p->EARxBpEB, scratch, n, r, k, /*divisor_log2*/12, stream);
    if (scratch_owned) cudaFreeAsync(scratch, stream);
    return rc;
#else
    auto* ws = static_cast<PearlCapiWorkspace*>(p->workspace);
    int device = ws ? ws->device_id : current_device_or(0);
    cudaDeviceProp* dprops = get_dprops_locked(device);
    if (!dprops) return -10;

    // Hard-coded defaults from pure-miner: tile_size_n / _k = nullopt
    // (kernel default 64x64 from heuristics.hpp), pipeline_stages = 2.
    const int tile_size_n = static_cast<int>(kDefaultNoisingTileSizeMN);
    const int tile_size_k = static_cast<int>(kDefaultNoisingTileSizeK);
    const int pipeline_stages = 2;

    PearlAPIParams params{};
    params.m = 0;  // unused for noise_B
    params.n = p->n;
    params.k = p->k;
    params.r = p->r;
    params.ptr_A = nullptr;
    params.ptr_B = p->B;
    params.ptr_EAL = nullptr;
    params.ptr_EAR_K_major = p->EAR_K_major;
    params.ptr_EBL_R_major = p->EBL_R_major;
    params.ptr_EAR_R_major = nullptr;
    params.ptr_EBL_K_major = nullptr;
    params.ptr_EBR = p->EBR;
    params.ptr_AxEBL = nullptr;
    params.ptr_EARxBpEB = p->EARxBpEB;  // fp16
    params.ptr_AxEBL_int32 = nullptr;
    params.ptr_EARxBpEB_int32 = nullptr;
    params.ptr_ApEA = nullptr;
    params.ptr_BpEB = p->BpEB;
    params.ptr_A_scales = nullptr;
    params.ptr_B_scales = nullptr;
    params.ptr_C = nullptr;
    params.host_signal_header_pinned = nullptr;
    params.host_signal_sync = nullptr;
    params.k_blocks_per_split_noising_A = 0;
    params.k_blocks_per_split_noising_B = 0;
    params.inner_hash_counter = nullptr;
    params.ptr_pow_target = nullptr;
    params.ptr_pow_key = nullptr;

    // Flat fp16 dispatch over (R, bK ∈ {64, 128}) at fixed bN=64,
    // stages=2. Mirrors NOISING_B_CONFIG_SWITCH for fp16 only.
    bool kernel_found = false;
    if (p->r == 64) {
      if (tile_size_k == 64) {
        run_pearl_noising_B_<cutlass::half_t, 64, 64, 64, 2>(params, stream);
        kernel_found = true;
      } else if (tile_size_k == 128) {
        run_pearl_noising_B_<cutlass::half_t, 64, 64, 128, 2>(params, stream);
        kernel_found = true;
      }
    } else if (p->r == 128) {
      if (tile_size_k == 64) {
        run_pearl_noising_B_<cutlass::half_t, 128, 64, 64, 2>(params, stream);
        kernel_found = true;
      } else if (tile_size_k == 128) {
        run_pearl_noising_B_<cutlass::half_t, 128, 64, 128, 2>(params, stream);
        kernel_found = true;
      }
    }
    if (!kernel_found) return -4;
    (void)tile_size_n; (void)pipeline_stages;
#endif  // PEARL_GEMM_PORTABLE
  } catch (const std::exception&) {
    return -2;
  }
  return 0;
}

PEARL_CAPI_EXPORT int pearl_capi_install_B(
    const PearlCapiInstallBParams* p,
    void* stream_void) {
  if (!p) return -1;
  if (!p->B || !p->BHash || !p->Key || !p->Roots || !p->AHash ||
      !p->CommitA || !p->CommitB || !p->EAR_K_major || !p->EBL_R_major ||
      !p->EBL_K_major || !p->EBR || !p->EBR_fp16 || !p->EARxBpEB ||
      !p->BpEB) {
    return -1;
  }
  if (p->expand_bseed && !p->bseed) return -1;

  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  cudaDeviceProp* dprops = get_dprops_locked(p->device_id);
  if (!dprops) return -10;
  const int64_t b_bytes = static_cast<int64_t>(p->n) * p->k;
  if (b_bytes < 0 || b_bytes > UINT32_MAX) return -11;

  try {
    if (p->expand_bseed) {
      if (p->LeafCvs) {
        bseed_expand_and_tensor_hash_with_leaf_cvs(
            p->bseed,
            static_cast<uint8_t*>(p->B),
            static_cast<uint32_t>(b_bytes),
            static_cast<uint8_t*>(p->BHash),
            static_cast<const uint8_t*>(p->Key),
            p->th_num_blocks,
            p->th_threads,
            p->th_stages,
            p->th_leaves,
            static_cast<uint8_t*>(p->Roots),
            static_cast<uint8_t*>(p->LeafCvs),
            *dprops,
            stream);
      } else {
        bseed_expand_and_tensor_hash(
          p->bseed,
          static_cast<uint8_t*>(p->B),
          static_cast<uint32_t>(b_bytes),
          static_cast<uint8_t*>(p->BHash),
          static_cast<const uint8_t*>(p->Key),
          p->th_num_blocks,
          p->th_threads,
          p->th_stages,
          p->th_leaves,
          static_cast<uint8_t*>(p->Roots),
          *dprops,
          stream);
      }
    } else {
      if (p->LeafCvs) {
        tensor_hash_with_leaf_cvs(
            static_cast<const uint8_t*>(p->B),
            static_cast<uint32_t>(b_bytes),
            static_cast<uint8_t*>(p->BHash),
            static_cast<const uint8_t*>(p->Key),
            p->th_num_blocks,
            p->th_threads,
            p->th_stages,
            p->th_leaves,
            static_cast<uint8_t*>(p->Roots),
            static_cast<uint8_t*>(p->LeafCvs),
            *dprops,
            stream);
      } else {
        tensor_hash(
          static_cast<const uint8_t*>(p->B),
          static_cast<uint32_t>(b_bytes),
          static_cast<uint8_t*>(p->BHash),
          static_cast<const uint8_t*>(p->Key),
          p->th_num_blocks,
          p->th_threads,
          p->th_stages,
          p->th_leaves,
          static_cast<uint8_t*>(p->Roots),
          *dprops,
          stream);
      }
    }
  } catch (const std::exception&) {
    return -2;
  }

  int rc = pearl_capi_commitment_hash_from_merkle_roots(
      static_cast<const uint8_t*>(p->AHash),
      static_cast<const uint8_t*>(p->BHash),
      static_cast<const uint8_t*>(p->Key),
      static_cast<uint8_t*>(p->CommitA),
      static_cast<uint8_t*>(p->CommitB),
      p->device_id,
      stream_void);
  if (rc != 0) return rc;

  rc = pearl_capi_noise_gen(
      p->r, p->m, p->n, p->k,
      nullptr, nullptr,
      nullptr, p->EAR_K_major,
      p->EBL_R_major, p->EBL_K_major,
      p->EBR, p->EBR_fp16,
      static_cast<const uint8_t*>(p->CommitA),
      static_cast<const uint8_t*>(p->CommitB),
      stream_void);
  if (rc != 0) return rc;

  PearlCapiNoiseBParams nb{};
  nb.n = p->n;
  nb.k = p->k;
  nb.r = p->r;
  nb.B = p->B;
  nb.EAR_K_major = p->EAR_K_major;
  nb.EBL_R_major = p->EBL_R_major;
  nb.EBR = p->EBR;
  nb.EARxBpEB = p->EARxBpEB;
  nb.BpEB = p->BpEB;
  nb.workspace = p->workspace;
  return pearl_capi_noise_B(&nb, stream_void);
}

PEARL_CAPI_EXPORT int pearl_capi_noisy_gemm(const PearlCapiNoisyGemmParams* p,
                                             void* stream_void) {
  if (!p) return -1;
  try {
    cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
#ifdef PEARL_GEMM_PORTABLE
    // Portable path — torch-free mirror of noisy_gemm_portable_impl in
    // csrc/gemm/pearl_gemm_api.cpp, compatible with sm_80/86/120a.
    //
    // Pure-miner-shaped flow (skip_denoising=true, skip_c_store=true,
    // run_noising_A=true, run_noising_B=false):
    //   1. ApEA = clamp(A + EAL @ EAR_R_major.T, ±127)
    //      AxEBL_fp16 = (A @ EBL_K_major.T) / 2^14
    //   2. (no noise_B inside noisy_gemm)
    //   3. transcript_gemm: full int8 GEMM ApEA(M,K) @ BpEB(N,K).T into
    //      C_running int32 + per-thread transcript snapshots every R cols.
    //   4. transcript_finalize: keyed BLAKE3 + atomic host_signal_header
    //      write on hit. Skip C bf16 store (skip_c_store=true).
    using namespace pearl::capi::portable;
    const int m = p->m, n = p->n, k = p->k, r = p->r;
    if (k % 32 != 0) return -22;
    if (r <= 0 || k % r != 0) return -23;

    // ── Step 1: noise_A portable ────────────────────────────────────────
    //   noise_A scratch is (m,r) for AxEBL fp16-div and (m,k) for ApEA
    //   add+clamp; the larger wins.
    int32_t* noiseA_scratch = nullptr;
    bool na_owned = false;
    auto* ws = static_cast<PearlCapiWorkspace*>(p->workspace);
    size_t na_bytes = std::max(scratch_bytes_for_matmul_i32(m, r),
                               scratch_bytes_for_matmul_i32(m, k));
    if (ws && ws->na_bytes >= na_bytes && ws->noiseA_ptr() != nullptr) {
      noiseA_scratch = static_cast<int32_t*>(ws->noiseA_ptr());
    } else {
      if (cudaMallocAsync(reinterpret_cast<void**>(&noiseA_scratch),
                          na_bytes, stream) != cudaSuccess) return -30;
      na_owned = true;
    }
    int rc = int8_matmul_into_fp16_div(
        static_cast<const int8_t*>(p->A),
        static_cast<const int8_t*>(p->EBL_K_major),
        p->AxEBL_fp16, noiseA_scratch, m, r, k, /*divisor_log2*/14, stream);
    if (rc == 0) {
      rc = int8_add_clamp_to_int8(
          static_cast<const int8_t*>(p->A),
          static_cast<const int8_t*>(p->EAL),
          static_cast<const int8_t*>(p->EAR_R_major),
          static_cast<int8_t*>(p->ApEA),
          noiseA_scratch, m, k, r, stream);
    }
    if (na_owned) cudaFreeAsync(noiseA_scratch, stream);
    if (rc != 0) return rc;

    // ── Step 2: transcript_gemm + target check ──────────────────────────
    // Pure-miner path: skip_c_store=true always, so no C buffer is ever
    // needed.  The reverse-engineered competing miner skips this too —
    // writing M·N·int32 (1 GiB) of dead C and the matching 1 GiB
    // cudaMallocAsync/Free was costing us per-iter wall time.
    //
    const int64_t batch = 1;

#if defined(PEARL_GEMM_VOLTA)
    cudaError_t launch_err = pearl::legacy::launch_transcript_gemm_dp4a_headless(
        static_cast<const int8_t*>(p->ApEA),
        static_cast<const int8_t*>(p->BpEB),
        /*C=*/nullptr,
        m, n, k, r, batch,
        static_cast<const uint32_t*>(p->pow_target),
        static_cast<const uint32_t*>(p->pow_key),
        static_cast<HostSignalSync*>(p->host_signal_sync),
        static_cast<HostSignalHeader*>(p->host_signal_header_pinned),
        stream);
    if (launch_err != cudaSuccess) return transcript_launch_rc(launch_err);

    (void)p->C; (void)p->A_scales; (void)p->B_scales;
    (void)p->EBR; (void)p->EBR_fp16; (void)p->EARxBpEB_fp16;
    (void)p->EAR_K_major; (void)p->EBL_R_major; (void)p->EAL_fp16;
    return 0;
#elif defined(PEARL_GEMM_TURING)
    cudaError_t launch_err = pearl::turing::launch_transcript_gemm_headless(
        static_cast<const int8_t*>(p->ApEA),
        static_cast<const int8_t*>(p->BpEB),
        /*C=*/nullptr,
        m, n, k, r, batch,
        static_cast<const uint32_t*>(p->pow_target),
        static_cast<const uint32_t*>(p->pow_key),
        static_cast<HostSignalSync*>(p->host_signal_sync),
        static_cast<HostSignalHeader*>(p->host_signal_header_pinned),
        stream);
    if (launch_err != cudaSuccess) return transcript_launch_rc(launch_err);

    (void)p->C; (void)p->A_scales; (void)p->B_scales;
    (void)p->EBR; (void)p->EBR_fp16; (void)p->EARxBpEB_fp16;
    (void)p->EAR_K_major; (void)p->EBL_R_major; (void)p->EAL_fp16;
    return 0;
#elif defined(PEARL_GEMM_BLACKWELL) || defined(PEARL_GEMM_ADA) || defined(PEARL_GEMM_AMPERE)
    // Production consumer mining is headless: keep the XOR transcript
    // in registers, emit only a winning host signal, and never spill the
    // transcript buffer to global memory. If PoW pointers are null this
    // intentionally emits nothing.
    cudaError_t launch_err = pearl::consumer::launch_transcript_gemm_headless(
        static_cast<const int8_t*>(p->ApEA),
        static_cast<const int8_t*>(p->BpEB),
        /*C=*/nullptr,
        m, n, k, r, batch,
        static_cast<const uint32_t*>(p->pow_target),
        static_cast<const uint32_t*>(p->pow_key),
        static_cast<HostSignalSync*>(p->host_signal_sync),
        static_cast<HostSignalHeader*>(p->host_signal_header_pinned),
        stream);
    if (launch_err != cudaSuccess) return transcript_launch_rc(launch_err);

    (void)p->C; (void)p->A_scales; (void)p->B_scales;
    (void)p->EBR; (void)p->EBR_fp16; (void)p->EARxBpEB_fp16;
    (void)p->EAR_K_major; (void)p->EBL_R_major; (void)p->EAL_fp16;
    return 0;
#endif

    // Portable/B200 fallback still uses the transcript spill + finalize path.
    // The portable kernel writes every slot unconditionally. B200's SM100
    // kernel combines snapshots with atomicXor, so the buffer must be zeroed.
    const int64_t transcript_elems =
        pearl::portable::transcript_buffer_elems(m, n, batch);

    uint32_t* transcript = nullptr;
    bool tr_owned = false;
    size_t tr_bytes = sizeof(uint32_t) * (size_t)transcript_elems;
    if (ws && ws->transcript_bytes >= tr_bytes &&
        ws->transcript_ptr() != nullptr) {
      transcript = static_cast<uint32_t*>(ws->transcript_ptr());
    } else {
      if (cudaMallocAsync(reinterpret_cast<void**>(&transcript),
                          tr_bytes, stream) != cudaSuccess) {
        return -32;
      }
      tr_owned = true;
    }

#ifdef PEARL_GEMM_B200
    if (cudaMemsetAsync(transcript, 0, tr_bytes, stream) != cudaSuccess) {
      if (tr_owned) cudaFreeAsync(transcript, stream);
      return -33;
    }
    cudaError_t transcript_err = pearl::portable::launch_transcript_gemm_sm100(
        static_cast<const int8_t*>(p->ApEA),
        static_cast<const int8_t*>(p->BpEB),
        transcript,
        m, n, k, r, batch, stream);
#else
#if defined(PEARL_GEMM_BLACKWELL)
    cudaError_t transcript_err = pearl::consumer::launch_transcript_gemm(
#else
    cudaError_t transcript_err = pearl::portable::launch_transcript_gemm(
#endif
        static_cast<const int8_t*>(p->ApEA),
        static_cast<const int8_t*>(p->BpEB),
        /*C=*/nullptr, transcript,
        m, n, k, r, batch, stream);
#endif
    if (transcript_err != cudaSuccess) {
      if (tr_owned) cudaFreeAsync(transcript, stream);
      return transcript_launch_rc(transcript_err);
    }

    pearl::portable::launch_transcript_finalize(
        transcript, m, n, batch,
        static_cast<const uint32_t*>(p->pow_target),
        static_cast<const uint32_t*>(p->pow_key),
        static_cast<HostSignalSync*>(p->host_signal_sync),
        static_cast<HostSignalHeader*>(p->host_signal_header_pinned),
        m, n, k, r, stream);
    cudaError_t finalize_err = cudaGetLastError();
    if (finalize_err != cudaSuccess) {
      if (tr_owned) cudaFreeAsync(transcript, stream);
      return transcript_finalize_rc(finalize_err);
    }

    if (tr_owned) cudaFreeAsync(transcript, stream);

    // skip_c_store == true → no bf16 epilogue needed (pure-miner default).
    (void)p->C; (void)p->A_scales; (void)p->B_scales;
    (void)p->EBR; (void)p->EBR_fp16; (void)p->EARxBpEB_fp16;
    (void)p->EAR_K_major; (void)p->EBL_R_major; (void)p->EAL_fp16;
    return 0;
#else
    auto* ws = static_cast<PearlCapiWorkspace*>(p->workspace);
    int device = ws ? ws->device_id : current_device_or(0);
    cudaDeviceProp* dprops = get_dprops_locked(device);
    if (!dprops) return -10;

    const int m = p->m, n = p->n, k = p->k, r = p->r;

    using ElementOut = cutlass::bfloat16_t;
    static constexpr int align_n = 128 / (sizeof(ElementOut) * 8);
    if (n % align_n != 0) return -5;
    if (k % p->bK != 0) return -6;
    if (p->bM > 256 || p->bN > 256) return -7;

    // Hard-coded constants from pure-miner's invocation of noisy_gemm:
    //   pipeline_stages = 3
    //   swizzle_n_maj   = true (auto swizzle from get_swizzle_size)
    //   noising tile sizes / stages_noising_* = defaults
    //   run_noising_A   = true, run_noising_B = false
    //   skip_reduction  = false
    //   skip_denoising  = true
    //   skip_c_store    = true
    //   AxEBL_int32 / EARxBpEB_int32 / inner_hash_counter = nullopt
    //   enable_debug    = false
    constexpr bool kSkipReduction = false;
    constexpr bool kSkipDenoising = true;
    constexpr bool kEnableDebug   = false;
    constexpr bool kSkipCStore    = true;
    constexpr bool kRunNoisingA   = true;
    constexpr int  kPipelineStages = 3;
    constexpr int  kPipelineStagesNoisingA = 2;
    constexpr bool kSwizzleNMaj   = true;
    const int tile_size_m_noising_A = static_cast<int>(kDefaultNoisingTileSizeMN);
    const int tile_size_k_noising_A = static_cast<int>(kDefaultNoisingTileSizeK);

    PearlAPIParams params{};
    params.m = m;
    params.n = n;
    params.k = k;
    params.r = r;
    params.swizzle = get_swizzle_size(k, kSwizzleNMaj ? p->bN : p->bM, dprops);
    params.swizzle_n_maj = kSwizzleNMaj;

    params.ptr_A   = p->A;
    params.ptr_B   = p->B;
    params.ptr_EAL = p->EAL;
    params.ptr_EAL_mma = p->EAL_fp16;
    params.ptr_EAR_R_major = p->EAR_R_major;
    params.ptr_EBL_R_major = p->EBL_R_major;
    params.ptr_EAR_K_major = p->EAR_K_major;
    params.ptr_EBL_K_major = p->EBL_K_major;
    params.ptr_EBR = p->EBR;
    params.ptr_EBR_mma = p->EBR_fp16;
    params.ptr_AxEBL = p->AxEBL_fp16;          // fp16 path
    params.ptr_AxEBL_int32 = nullptr;
    params.ptr_EARxBpEB = p->EARxBpEB_fp16;    // fp16 path
    params.ptr_EARxBpEB_int32 = nullptr;
    params.ptr_AxEBL_mma = p->AxEBL_fp16;
    params.ptr_EARxBpEB_mma = p->EARxBpEB_fp16;
    params.ptr_ApEA = p->ApEA;
    params.ptr_BpEB = p->BpEB;
    params.ptr_A_scales = p->A_scales;
    params.ptr_B_scales = p->B_scales;
    params.ptr_C = p->C;
    params.host_signal_header_pinned = p->host_signal_header_pinned;
    params.host_signal_sync = p->host_signal_sync;
    params.k_blocks_per_split_noising_A = 0;
    params.k_blocks_per_split_noising_B = 0;
    params.inner_hash_counter = nullptr;
    params.ptr_pow_target = p->pow_target;
    params.ptr_pow_key    = p->pow_key;

    // Noising A (fp16, no split-K).
    if constexpr (kRunNoisingA) {
      bool found = false;
      if (r == 64) {
        if (tile_size_k_noising_A == 64) {
          run_pearl_noising_A_<cutlass::half_t, 64, 64, 64, kPipelineStagesNoisingA>(params, stream);
          found = true;
        } else if (tile_size_k_noising_A == 128) {
          run_pearl_noising_A_<cutlass::half_t, 64, 64, 128, kPipelineStagesNoisingA>(params, stream);
          found = true;
        }
      } else if (r == 128) {
        if (tile_size_k_noising_A == 64) {
          run_pearl_noising_A_<cutlass::half_t, 128, 64, 64, kPipelineStagesNoisingA>(params, stream);
          found = true;
        } else if (tile_size_k_noising_A == 128) {
          run_pearl_noising_A_<cutlass::half_t, 128, 64, 128, kPipelineStagesNoisingA>(params, stream);
          found = true;
        }
      }
      if (!found) return -8;
      (void)tile_size_m_noising_A;
    }

    // Matmul: enumerate the pre-instantiated (R, bM, bN, bK, stages, cM, cN)
    // tuples (mirrors static_switch_matmul.h after expansion).
    const int bM = static_cast<int>(p->bM);
    const int bN = static_cast<int>(p->bN);
    const int bK = static_cast<int>(p->bK);
    const int cM = static_cast<int>(p->cM);
    const int cN = static_cast<int>(p->cN);

    bool matmul_found = false;
    if (bM == 128 && bN == 256 && bK == 128 && kPipelineStages == 3 && cM == 1 && cN == 1) {
      if (r == 64) {
        run_pearl_gemm_<ElementOut, 64, 128, 256, 128, 3, 1, 1,
                        kSkipReduction, kSkipDenoising, kEnableDebug,
                        kSkipCStore>(params, stream);
        matmul_found = true;
      } else if (r == 128) {
        run_pearl_gemm_<ElementOut, 128, 128, 256, 128, 3, 1, 1,
                        kSkipReduction, kSkipDenoising, kEnableDebug,
                        kSkipCStore>(params, stream);
        matmul_found = true;
      }
    }
    if (!matmul_found) return -9;
#endif  // PEARL_GEMM_PORTABLE
  } catch (const std::exception&) {
    return -2;
  }
  return 0;
}

// ── pearl_capi_workspace_install_params ────────────────────────────────────
// Stores all per-σ constants into the workspace so pearl_capi_iter can avoid
// re-passing them on every iteration.  The noisy_gemm template struct is also
// pre-built here so per-iter only the host_signal_header_pinned field is patched.
PEARL_CAPI_EXPORT int pearl_capi_workspace_install_params(
    void* workspace_ptr, const PearlCapiWorkspaceParams* p) {
  if (!workspace_ptr || !p) return -1;
  auto* ws = static_cast<PearlCapiWorkspace*>(workspace_ptr);

  destroy_iter_graph(ws);
  ws->params = *p;
  ws->device_id = current_device_or(0);

  // Pre-build the noisy_gemm param struct — everything except
  // host_signal_header_pinned is constant for the σ lifetime.
  PearlCapiNoisyGemmParams ng{};
  ng.m  = p->m;  ng.n  = p->n;  ng.k  = p->k;  ng.r  = p->r;
  ng.bM = p->bM; ng.bN = p->bN; ng.bK = p->bK;
  ng.cM = p->cM; ng.cN = p->cN;
  ng.A             = p->A;
  ng.B             = p->B;
  ng.EAL           = p->EAL;
  ng.EAL_fp16      = p->EAL_fp16;
  ng.EBR           = p->EBR;
  ng.EBR_fp16      = p->EBR_fp16;
  ng.EAR_R_major   = p->EAR_R_major;
  ng.EBL_R_major   = p->EBL_R_major;
  ng.EAR_K_major   = p->EAR_K_major;
  ng.EBL_K_major   = p->EBL_K_major;
  ng.AxEBL_fp16    = p->AxEBL_fp16;
  ng.EARxBpEB_fp16 = p->EARxBpEB_fp16;
  ng.ApEA          = p->ApEA;
  ng.BpEB          = p->BpEB;
  ng.A_scales      = p->A_scales;
  ng.B_scales      = p->B_scales;
  ng.C             = p->C;
  ng.host_signal_header_pinned = nullptr;  // patched per-iter by pearl_capi_iter
  ng.host_signal_sync          = p->host_signal_sync;
  ng.pow_target                = p->pow_target;
  ng.pow_key                   = p->pow_key;
  ng.workspace                 = workspace_ptr;

  ws->ng_template      = ng;
  ws->params_installed = true;
  return 0;
}

// ── pearl_capi_iter ────────────────────────────────────────────────────────
// Single per-iteration call that replaces 5 separate CAPI calls in the hot
// loop (LcgInt7Fill + TensorHash + CommitHash + NoiseGen_A + NoisyGemm).
// Only seed_lo (nonce counter) and host_signal_header_pinned (pinned host
// slot for this iteration) vary; all other params come from the workspace.
// All kernel launches are enqueued on `stream` in FIFO order.
PEARL_CAPI_EXPORT int pearl_capi_iter(void*    workspace_ptr,
                                      uint64_t seed_lo,
                                      void*    host_signal_header_pinned,
                                      void*    stream_void) {
  if (!workspace_ptr) return -1;
  auto* ws = static_cast<PearlCapiWorkspace*>(workspace_ptr);
  if (!ws->params_installed) return -3;

  const PearlCapiWorkspaceParams& p = ws->params;
  const int device_id = ws->device_id;
  int rc;

  // 1. Fill A with deterministic int7 values for this nonce.
  rc = pearl_capi_lcg_int7_fill(p.A, (int64_t)p.m * p.k,
                                 seed_lo, p.sigma_seed, stream_void);
  if (rc != 0) return rc;

  // 2. Hash A → AHash (Merkle tree root).
  rc = pearl_capi_tensor_hash(
      static_cast<const uint8_t*>(p.A),
      static_cast<uint32_t>((int64_t)p.m * p.k),
      static_cast<uint8_t*>(p.AHash),
      static_cast<const uint8_t*>(p.Key),
      p.th_num_blocks, p.th_threads, p.th_stages, p.th_leaves,
      static_cast<uint8_t*>(p.Roots), device_id, stream_void);
  if (rc != 0) return rc;

  // 3. Commitment hash: (AHash, BHash) → CommitA, CommitB.
  rc = pearl_capi_commitment_hash_from_merkle_roots(
      static_cast<const uint8_t*>(p.AHash),
      static_cast<const uint8_t*>(p.BHash),
      static_cast<const uint8_t*>(p.Key),
      static_cast<uint8_t*>(p.CommitA),
      static_cast<uint8_t*>(p.CommitB),
      device_id, stream_void);
  if (rc != 0) return rc;

  // 4. Noise-gen A only (B-side computed once at σ-install).
  rc = pearl_capi_noise_gen(
      p.r, p.m, p.n, p.k,
      p.EAL, p.EAL_fp16,
      p.EAR_R_major, p.EAR_K_major,
      nullptr, nullptr, nullptr, nullptr,
      static_cast<const uint8_t*>(p.CommitA), nullptr, stream_void);
  if (rc != 0) return rc;

  // 5. Noisy GEMM — copy template and patch only the per-iter header pointer.
  PearlCapiNoisyGemmParams ng = ws->ng_template;
  ng.host_signal_header_pinned = host_signal_header_pinned;
  return pearl_capi_noisy_gemm(&ng, stream_void);
}

// Batched variant of pearl_capi_iter(). Keeps kernel sequencing identical to
// calling pearl_capi_iter() in a for-loop, but removes repeated managed/native
// boundary crossings in the miner hot path.
PEARL_CAPI_EXPORT int pearl_capi_iter_batch(
    void*        workspace_ptr,
    uint64_t     seed_lo_start,
    void* const* host_signal_header_pinned_batch,
    int32_t      count,
    void*        stream_void) {
  if (!workspace_ptr) return -1;
  if (count < 0) return -1;
  if (count > 0 && !host_signal_header_pinned_batch) return -1;

  auto* ws = static_cast<PearlCapiWorkspace*>(workspace_ptr);
  if (!ws->params_installed) return -3;

  for (int32_t i = 0; i < count; ++i) {
    int rc = pearl_capi_iter(workspace_ptr,
                             seed_lo_start + static_cast<uint64_t>(i),
                             host_signal_header_pinned_batch[i],
                             stream_void);
    if (rc != 0) return rc;
  }
  return 0;
}

PEARL_CAPI_EXPORT int pearl_capi_iter_batch_graph_prepare(
    void*        workspace_ptr,
    void* const* host_signal_header_pinned_batch,
    int32_t      count,
    void*        stream_void) {
  if (!workspace_ptr) return -1;
  if (count <= 0) return -1;
  if (!host_signal_header_pinned_batch) return -1;

  auto* ws = static_cast<PearlCapiWorkspace*>(workspace_ptr);
  if (!ws->params_installed) return -3;

  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  const PearlCapiWorkspaceParams& p = ws->params;
  const int device_id = ws->device_id;
  const int64_t a_bytes = static_cast<int64_t>(p.m) * p.k;

  destroy_iter_graph(ws);

  cudaError_t err = cudaHostAlloc(
      reinterpret_cast<void**>(&ws->graph_seed_lo_host),
      sizeof(uint64_t), cudaHostAllocPortable);
  if (err != cudaSuccess) {
    destroy_iter_graph(ws);
    return -40;
  }
  *ws->graph_seed_lo_host = 0;

  err = cudaMalloc(reinterpret_cast<void**>(&ws->graph_seed_lo_dev),
                   sizeof(uint64_t));
  if (err != cudaSuccess) {
    destroy_iter_graph(ws);
    return -41;
  }

  cudaDeviceProp* dprops = get_dprops_locked(device_id);
  if (!dprops) {
    destroy_iter_graph(ws);
    return -10;
  }

  try {
    tensor_hash_set_key(static_cast<const uint8_t*>(p.Key), stream);
  } catch (const std::exception&) {
    destroy_iter_graph(ws);
    return -42;
  }

  err = cudaStreamSynchronize(stream);
  if (err != cudaSuccess) {
    destroy_iter_graph(ws);
    return -43;
  }

  bool capturing = false;
  auto abort_capture = [&]() {
    if (capturing) {
      cudaGraph_t aborted = nullptr;
      (void)cudaStreamEndCapture(stream, &aborted);
      if (aborted) cudaGraphDestroy(aborted);
      capturing = false;
    }
    destroy_iter_graph(ws);
  };

  err = cudaStreamBeginCapture(stream, cudaStreamCaptureModeRelaxed);
  if (err != cudaSuccess) {
    destroy_iter_graph(ws);
    return -44;
  }
  capturing = true;

  err = cudaMemcpyAsync(ws->graph_seed_lo_dev, ws->graph_seed_lo_host,
                        sizeof(uint64_t), cudaMemcpyHostToDevice, stream);
  if (err != cudaSuccess) {
    abort_capture();
    return -45;
  }

  err = cudaMemsetAsync(p.host_signal_sync, 0, sizeof(HostSignalSync), stream);
  if (err != cudaSuccess) {
    abort_capture();
    return -46;
  }

  for (int32_t i = 0; i < count; ++i) {
    int rc = pearl_capi_lcg_int7_fill_indirect(
        p.A, a_bytes, ws->graph_seed_lo_dev,
        static_cast<uint64_t>(i), p.sigma_seed, stream_void);
    if (rc != 0) {
      abort_capture();
      return rc;
    }

    try {
      tensor_hash_no_key_upload(
          static_cast<const uint8_t*>(p.A),
          static_cast<uint32_t>(a_bytes),
          static_cast<uint8_t*>(p.AHash),
          static_cast<const uint8_t*>(p.Key),
          p.th_num_blocks, p.th_threads, p.th_stages, p.th_leaves,
          static_cast<uint8_t*>(p.Roots), *dprops, stream);
    } catch (const std::exception&) {
      abort_capture();
      return -2;
    }

    rc = pearl_capi_commitment_hash_from_merkle_roots(
        static_cast<const uint8_t*>(p.AHash),
        static_cast<const uint8_t*>(p.BHash),
        static_cast<const uint8_t*>(p.Key),
        static_cast<uint8_t*>(p.CommitA),
        static_cast<uint8_t*>(p.CommitB),
        device_id, stream_void);
    if (rc != 0) {
      abort_capture();
      return rc;
    }

    rc = pearl_capi_noise_gen(
        p.r, p.m, p.n, p.k,
        p.EAL, p.EAL_fp16,
        p.EAR_R_major, p.EAR_K_major,
        nullptr, nullptr, nullptr, nullptr,
        static_cast<const uint8_t*>(p.CommitA), nullptr, stream_void);
    if (rc != 0) {
      abort_capture();
      return rc;
    }

    PearlCapiNoisyGemmParams ng = ws->ng_template;
    ng.host_signal_header_pinned = host_signal_header_pinned_batch[i];
    rc = pearl_capi_noisy_gemm(&ng, stream_void);
    if (rc != 0) {
      abort_capture();
      return rc;
    }
  }

  cudaGraph_t graph = nullptr;
  err = cudaStreamEndCapture(stream, &graph);
  capturing = false;
  if (err != cudaSuccess || !graph) {
    destroy_iter_graph(ws);
    return -47;
  }
  ws->iter_graph = graph;

  err = cudaGraphInstantiate(&ws->iter_graph_exec, ws->iter_graph, 0);
  if (err != cudaSuccess) {
    destroy_iter_graph(ws);
    return -48;
  }

  err = cudaGraphUpload(ws->iter_graph_exec, stream);
  if (err != cudaSuccess) {
    destroy_iter_graph(ws);
    return -49;
  }
  err = cudaStreamSynchronize(stream);
  if (err != cudaSuccess) {
    destroy_iter_graph(ws);
    return -50;
  }

  ws->graph_batch_count = count;
  ws->graph_ready = true;
  return 0;
}

PEARL_CAPI_EXPORT int pearl_capi_iter_batch_graph_launch(
    void* workspace_ptr,
    uint64_t seed_lo_start,
    void* stream_void) {
  if (!workspace_ptr) return -1;
  auto* ws = static_cast<PearlCapiWorkspace*>(workspace_ptr);
  if (!ws->params_installed) return -3;
  if (!ws->graph_ready || !ws->iter_graph_exec ||
      !ws->graph_seed_lo_host || !ws->graph_seed_lo_dev ||
      ws->graph_batch_count <= 0) {
    return -51;
  }

  *ws->graph_seed_lo_host = seed_lo_start;
  cudaStream_t stream = static_cast<cudaStream_t>(stream_void);
  cudaError_t err = cudaGraphLaunch(ws->iter_graph_exec, stream);
  return (err == cudaSuccess) ? 0 : -static_cast<int>(err);
}

}  // extern "C"
